### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by arkilis** [middlefeng/NuoModelViewer#1]
Hi thanks for your awesome project and sharing, 

I have the following error while open the `ModelViewer.xcodeproj`:

`/Users/ben/ben_ws/mac_dev/NuoModelViewer/ModelViewer/ViewerFoundation/Meshes/ShadersCommon.h:66:52: 'function_constant' attribute requires metal language to be 1.2 or higher`

Pretty much new to metal, any tips on this? Thanks

**Comment by middlefeng** [comment]
@arkilis The latest project is for macOS 10.13 beta with Xcode 9. Use the one with suffix `-Old` in 10.12.

**Comment by arkilis** [comment]
Just curious, if you update your Xcode to Xcode 9, how would you deal with issue that the Swift 4 will be the default version and the pervious Swift 3 is not working any more?

**Comment by middlefeng** [comment]
@arkilis No swift code in this project. It's all Objective-C, C, and C++.
