### ISSUE TITLE
 Compiler failed with XPC_ERROR_CONNECTION_INTERRUPTED

### ISSUE THREAD

**Issue by Goallying** [middlefeng/NuoModelViewer#3]

**Comment by middlefeng** [comment]
To my understanding, this is a *runtime* error rather than a compile failure, is it? Metal 2 has some severe bugs on macOS 10.13.1. Please make sure you upgrade to the latest 10.13.3.

**Comment by middlefeng** [comment]
@Goallying Please provide further details or the issue will be closed.

**Comment by Goallying** [comment]
i download  and run ,then this error occured!! ,my OSX 10.12.6. my Xocde 9.2

**Comment by middlefeng** [comment]
@Goallying Unfortunately, Apple does not make Metal stable enough before 10.13.4. You have to install 10.13.4 and Xcode 9.3 to build and run the app.

**Comment by Goallying** [comment]
ok, thanks .
