### ISSUE TITLE
Compiler failed with XPC_ERROR_CONNECTION_INTERRUPTED - OS:10.13.6, XCode9.4.1

### ISSUE THREAD

**Issue by jack89zhao** [middlefeng/NuoModelViewer#4]

**Comment by middlefeng** [comment]
@jack89zhao Are you on the `master` branch?

**Comment by middlefeng** [comment]
To collect more information, have you tested on another macOS/Xcode version? I'm using macOS 10.13.4 with Xcode 9.4 and I cannot reproduce the problem.

**Comment by jack89zhao** [comment]
yes. I’m on the master branch.

and I tried on the xcode 10.0(beta 5), the problem still exists.

Best Regards

**Comment by middlefeng** [comment]
@jack89zhao What's your GPU? Is it AMD or Nvidia (which must be pre-2015 model)?

**Comment by jack89zhao** [comment]
The GPU is intel, Intel Iris Pro. It's an Integrated GPU.

**Comment by middlefeng** [comment]
Unfortunately, the features of Metal driver used by this program are not working with Iris Pro. It's either my code not well compatible, or Apple's driver's defect. I'm afraid I don't have an ETA of whether or when I could fix it.
