### ISSUE TITLE
The Project still cannot work on my Mac based on Intel Iris Graphics

### ISSUE THREAD

**Issue by kirinzer** [middlefeng/NuoModelViewer#5]
So, what should I do to fix it?

**Comment by middlefeng** [comment]
This is similar to https://github.com/middlefeng/NuoModelViewer/issues/4.
Iris driver seemed buggy and low priority in Apple's support. Unfortunately I don't have plan (or think I would get necessary support from Apple) to fix it.

**Comment by kirinzer** [comment]
It is so sad, it the worst thing that I've heard today
